# Generated by Django 4.0.1 on 2022-01-26 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPayType', models.BooleanField(default=False)),
                ('isPO', models.BooleanField(default=False)),
                ('isMVP', models.BooleanField(default=True)),
                ('isFromScratch', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TeamsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devMetodology', models.CharField(max_length=101)),
                ('analitics', models.IntegerField(default=0)),
                ('tester', models.IntegerField(default=0)),
                ('back', models.IntegerField(default=0)),
                ('front', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=101)),
                ('procedure', models.CharField(max_length=100)),
                ('isOvertimeExpect', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(default=None, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('project_name', models.CharField(max_length=101)),
                ('customer', models.CharField(max_length=100)),
                ('proj_stage', models.CharField(max_length=100)),
                ('technology', models.CharField(max_length=100)),
                ('func_direction', models.CharField(max_length=100)),
                ('subject_area', models.CharField(max_length=100)),
                ('draft', models.BooleanField(default=False)),
                ('project_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='rechappines.projectstype')),
                ('team_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='rechappines.teamsinfo')),
                ('working_conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='rechappines.workingcondition')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
