# Generated by Django 4.0.1 on 2022-01-27 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechappines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='id',
        ),
        migrations.AlterField(
            model_name='technology',
            name='tech',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
