# Generated by Django 4.0.1 on 2022-01-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rechappines', '0002_remove_technology_id_alter_technology_tech'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='storage')),
                ('file_custom_name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
